import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import "./globals.css";

// const UserProvider = dynamic(
//   async () => (await import("@/components/UserProvider")).UserProvider,
//   {
//     ssr: false,
//   }
// );

export const metadata: Metadata = {
  title: "SwiftPOS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { 

  return (
    <html lang="en" suppressHydrationWarning={true} className={GeistSans.className}>
      <body className='antialiased'>
          {children}
      </body>
    </html>
  );
}
